.github/pull_request_template.md
src/main/java/com/umc/yourweather/auth/CustomUserDetails.java
src/main/java/com/umc/yourweather/domain/Role.java
src/main/java/com/umc/yourweather/domain/User.java
src/main/java/com/umc/yourweather/jwt/filter/CustomLoginFilter.java
src/main/java/com/umc/yourweather/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/umc/yourweather/repository/UserRepository.java
src/main/java/com/umc/yourweather/repository/impl/UserRepositoryImpl.java
src/main/java/com/umc/yourweather/repository/jpa/UserJpaRepository.java

> 요청 시 인증에 대한 필터를 만들었습니다.
- 매 요청 마다 토큰의 유효성을 판별하는 필터
- /login 요청 시 request의 body를 읽어서 로그인 인증을 해주는 필터
- User에 Role 필드가 필요해 추가했습니다.
- Role은 User의 권한을 나타내는 필드입니다.
- CustomUserDetails를 추가했습니다.
- 유저의 Authentication 정보를 만들기 위해 필요한 UserDetails 구현체입니다.
- User 엔티티를 CustomUserDetails에 담아서 여러 메서드에 User 엔티티의 필드를 사용하도록 하기 위해서 넣은 것입니다.
- 그 외에는 Repository 메서드들의 반환 타입을 Optional로 수정했습니다.
- 직접 다뤄보니 필터에서 유연하게 repository를 쓰려면 Optional인 것이 더 편한 것 같아서 수정했습니다.

5 featureauthenticationfilters

---

src/main/java/com/umc/yourweather/auth/CustomUserDetails.java
src/main/java/com/umc/yourweather/auth/CustomUserDetailsService.java
src/main/java/com/umc/yourweather/domain/User.java
src/main/java/com/umc/yourweather/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/umc/yourweather/jwt/handler/LoginFailureHandler.java
src/main/java/com/umc/yourweather/jwt/handler/LoginSuccessHandler.java

> CustomUserDetailsService를 만들어 유저 인증 부분을 완성했습니다. 추가로 로그인 성공 핸들러, 로그인 실패 핸들러를 만들어줬습니다.
- CustomUserDetailsService
- LoginSuccessHandler
- LoginFailureHandler
- 그 외로는 User 필드를 수정했습니다.
- userPw -> password
- provider -> platform
- providerId -> X
- 해당 필드는 큰 용도가 없어서 지워버렸습니다. 나중에 혹시라도 필요하다면 다시 필드를 추가해봅시당

7 feat/CustomUserDetailsService

---

src/main/java/com/umc/yourweather/auth/CustomUserDetails.java

feat : create getUser()

---

src/main/java/com/umc/yourweather/controller/UserController.java
src/main/java/com/umc/yourweather/domain/User.java
src/main/java/com/umc/yourweather/dto/LoginRequestDto.java
src/main/java/com/umc/yourweather/dto/ResponseDto.java
src/main/java/com/umc/yourweather/dto/SignupRequestDto.java
src/main/java/com/umc/yourweather/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/umc/yourweather/repository/UserRepository.java
src/main/java/com/umc/yourweather/repository/impl/UserRepositoryImpl.java
src/main/java/com/umc/yourweather/repository/jpa/UserJpaRepository.java
src/main/java/com/umc/yourweather/service/UserService.java
src/test/java/com/umc/yourweather/controller/UserControllerTest.java
src/test/java/com/umc/yourweather/jwt/JwtTokenManagerTest.java

회원 가입 기능을 구현하였습니다. 이에 따라 추가적인 패키지와 `java` 파일들이 추가되었습니다. 
(`UserController.java`, `UserService.java`, `SignupRequestDto.java`, `ResponseDto.java`) 
회원 가입 성공 시 HTTP 상태 코드 200을 넘겨주도록 구현하였습니다. 
- **소셜 로그인와 일반 로그인 구분**
소셜 로그인의 경우 password가 넘어오지 않습니다. 따라서 소셜 로그인의 경우 임의의 값을 password 필드에 넣는 로직을 추가하였습니다.
```java
if (password == null) {
password = UUID.randomUUID().toString();
}
```
- **ResponseDto**
success, code, message, result 네 개의 필드를 받습니다. 
```java
private final boolean success;
private final int code;
private final String message;
@JsonInclude(JsonInclude.Include.NON_NULL)
private final T result;
```
- **User.java access 권한 변경** 
```java
// 기존
@NoArgsConstructor()
// 변경
@NoArgsConstructor(access = AccessLevel.PROTECTED)
```
- UserService 상단에 `@Transaction(readonly = true)` 를  설정한 뒤, 트랜섹션이 …

[FEAT] Sign Up

---

src/main/java/com/umc/yourweather/auth/CustomUserDetails.java
src/main/java/com/umc/yourweather/config/SecurityConfig.java
src/main/java/com/umc/yourweather/domain/User.java
src/main/java/com/umc/yourweather/jwt/filter/CustomLoginFilter.java
src/main/java/com/umc/yourweather/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/umc/yourweather/jwt/handler/LoginFailureHandler.java
src/main/java/com/umc/yourweather/jwt/handler/LoginSuccessHandler.java
src/test/java/com/umc/yourweather/jwt/JwtTokenManagerTest.java

> SecurityConfig를 설정해줬습니다.
- SecurityConfig 설정
- 현재 테스트는 모두 통과한 상황입니다.
- Postman을 이용해 회원가입, 로그인을 테스트해봤습니다.
- 회원가입은 정말 단순하게 구현했고, 해당 브랜치에는 테스트용 회원가입 로직은 포함되어있지 않습니다.

[FEAT] SecurityConfig

---

build.gradle
src/main/java/com/umc/yourweather/config/RedisConfig.java
src/main/java/com/umc/yourweather/controller/EmailController.java
src/main/java/com/umc/yourweather/repository/redis/EmailCodeRedisRepository.java
src/main/java/com/umc/yourweather/service/EmailService.java

> 이메일 인증코드를 확인해줍니다.
- 이메일 전송 시 Redis에 인증코드 저장
- /certify 요청 시 Redis에 있는 값 비교
- 만약 인증이 성공했으면 result에 true를 넣어서 전달, 아닐 경우 false 전달

25 email certicifier

---

src/main/java/com/umc/yourweather/auth/CustomUserDetails.java
src/main/java/com/umc/yourweather/auth/CustomUserDetailsService.java
src/main/java/com/umc/yourweather/domain/User.java
src/main/java/com/umc/yourweather/jwt/JwtTokenManager.java
src/main/java/com/umc/yourweather/jwt/filter/CustomLoginFilter.java
src/main/java/com/umc/yourweather/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/umc/yourweather/jwt/handler/LoginFailureHandler.java
src/main/java/com/umc/yourweather/jwt/handler/LoginSuccessHandler.java
src/main/java/com/umc/yourweather/repository/impl/UserRepositoryImpl.java
src/main/java/com/umc/yourweather/service/UserService.java

> 그 동안 main에 merge된 코드들 중, Google Java Style Guide에 맞지 않는 코드들을 교정했습니다.
- 코드들 전부 컨벤션에 맞게 수정

18-main refactoring

---

src/main/java/com/umc/yourweather/api/RequestURI.java
src/main/java/com/umc/yourweather/controller/EmailController.java
src/main/java/com/umc/yourweather/controller/UserController.java

> RequestURI를 더 안전하게 수정했습니다. 추가로 static 변수에 알맞는 네이밍으로 변경했습니다.
- commonURI = "/api/v1/" -> CURRENT_VER = "/api/v1"
- USER_URI = CURRENT_VER + "/users"
- EMAIL_URI = CURRENT_VER + "/email"
- 이렇게 만든 이유는 컨트롤러에 쓰일 URI를 만들면서 문자열 연산에 사용되어지는 변수를 한번에 확인할 수 있기 때문에 더 안전하기 때문입니다.

31 requesturi fix

---

src/main/java/com/umc/yourweather/YourweatherApplication.java
src/main/java/com/umc/yourweather/controller/EmailController.java
src/main/java/com/umc/yourweather/service/EmailService.java

> email 전송을 비동기 처리했습니다. 테스트도 통과했습니다.
- email 전송 비동기 처리

29 async email send

---

src/main/java/com/umc/yourweather/api/RequestURI.java
src/main/java/com/umc/yourweather/controller/WeatherController.java
src/main/java/com/umc/yourweather/domain/Memo.java
src/main/java/com/umc/yourweather/exception/GlobalExceptionHandler.java
src/main/java/com/umc/yourweather/exception/MemoNotFoundException.java
src/main/java/com/umc/yourweather/exception/WeatherNotFoundException.java
src/main/java/com/umc/yourweather/request/MissedInputRequestDto.java
src/main/java/com/umc/yourweather/response/MissedInputResponseDto.java
src/main/java/com/umc/yourweather/service/WeatherService.java

> DELETE /api/v1/weather/{year}-{month}-{day}
- 삭제 기능 추가 
- Repository 조회 시 User를 넘겨주는 것은 반영하지 않았습니다. (추후에 main branch 당겨온 후 작업) 
- Report와 관련된 사항들은 모두 삭제했습니다. (혹시 모를 충돌에 대비해)

49 delete weather

---

src/main/java/com/umc/yourweather/controller/ReportController.java
src/main/java/com/umc/yourweather/domain/Statistic.java
src/main/java/com/umc/yourweather/domain/StatisticCreator.java
src/main/java/com/umc/yourweather/request/SignupRequestDto.java
src/main/java/com/umc/yourweather/response/StatisticResponseDto.java
src/main/java/com/umc/yourweather/service/ReportService.java

> 주간/월간 대비 통계 분석을 할 수 있습니다.
- 주간 대비 통계 분석 
- 월간 대비 통계 분석
- 현재 인수테스트만 시행한 상태입니다.
- 나중에 테스트 코드를 써야겠습니다
- 지금 현재 GUI를 잘못 이해해서 비교를 이전의 특정 주/월 데이터와 비교 가능하게 뒀는데, 현재 개발한게 요구사항보다 더 큰범위니까 로직 수정은 안하거나 조금만 수정하면 될 것 같습니다.
- **요구사항: 직전 주/월과 이번 주/월 비교분석**
- **만든 것: 특정 주/월(선택 가능) 이번 주/월 비교 분석**
- **++ request parameter를 선택 여부로 뒀습니다. request parameter를 안 건내준다면 직전 주/월, 현재 주/월 과 비교, 특정 값을 넣었다면 특정 주/월, 현재 주/월 이렇게요!**

57 weekly-monthly contrast indicator

---

build.gradle
src/main/java/com/umc/yourweather/controller/MemoController.java
src/main/java/com/umc/yourweather/controller/UserController.java
src/main/java/com/umc/yourweather/controller/WeatherController.java

>  `WeatherController.java`, `MemoController.java` 에 대한 API 명세 추가 
- API 명세 추가

[FEAT] Swagger API 명세 추가

---

src/main/java/com/umc/yourweather/controller/EmailController.java
src/main/java/com/umc/yourweather/controller/ReportController.java
src/main/java/com/umc/yourweather/domain/entity/User.java
src/main/java/com/umc/yourweather/domain/entity/Weather.java
src/main/java/com/umc/yourweather/jwt/filter/JwtAuthenticationFilter.java

> 션이 개발한 api 에 대한 명세를 적어놨습니다
- 명세 작성
- 실제 작동 테스트
- 필터에서 테스트 용으로 sout 하던 걸 지웠습니다
- orphanRemoval -> cascade로 수정했습니다

63 api spec sean

---

src/main/java/com/umc/yourweather/controller/MemoController.java
src/main/java/com/umc/yourweather/domain/Memo.java
src/main/java/com/umc/yourweather/domain/entity/Memo.java
src/main/java/com/umc/yourweather/repository/MemoRepository.java
src/main/java/com/umc/yourweather/repository/impl/MemoRepositoryImpl.java
src/main/java/com/umc/yourweather/repository/jpa/MemoJpaRepository.java
src/main/java/com/umc/yourweather/request/MemoUpdateRequestDto.java
src/main/java/com/umc/yourweather/response/MemoUpdateResponseDto.java
src/main/java/com/umc/yourweather/response/ResponseDto.java
src/main/java/com/umc/yourweather/service/MemoService.java
src/test/java/com/umc/yourweather/repository/test/MemoTestRepository.java

> memo 수정/삭제 기능구현
- [수정] 
MemoController의 update에서 memoService의 update호출 -> memoService에서 memoRepository.findById(id)로 수정하고자하는 게시글이 있는지 탐색 -> Memo의 Update 메소드 호출
- [삭제] 
MemoController의 delete에서 memoService의 delete호출 -> memoService에서 memoRepository.findById(id)로 삭제하고자하는 게시글이 있는지 탐색 -> JpaRepository에서 제공하고 있는 delete 메소드 사용
-

[FEAT] memo delete and update

---

src/main/java/com/umc/yourweather/request/MemoRequestDto.java
src/main/java/com/umc/yourweather/request/MissedInputRequestDto.java
src/main/java/com/umc/yourweather/request/SignupRequestDto.java
src/main/java/com/umc/yourweather/request/WeatherRequestDto.java
src/main/java/com/umc/yourweather/response/MemoResponseDto.java
src/main/java/com/umc/yourweather/service/MemoService.java
src/test/java/com/umc/yourweather/repository/test/MemoTestRepository.java
src/test/java/com/umc/yourweather/service/MemoServiceTest.java

> int year, month, day, hour, minute, second로 이어지는 긴 요청을 LocalDateTime으로 변경
- 프론트에서는 LocalDateTime.toString() 으로 요청을 보내고, 받을 때는 해당 문자열을 LocalDateTime.parse()로 변환해주는 작업을 거치면 기존 로직과 동일하게 처리 가능

[FEAT] Change Memo Request API

---

src/main/java/com/umc/yourweather/config/LoginEndpointCustomizer.java
src/main/java/com/umc/yourweather/config/SpringDocsConfig.java

> 로그인 필터를 컨트롤러로 옮기지 않고 직접 OpenApiCustomizer를 만들어서 스웨거에 등록을 해줬습니다
- 로그인 필터 스웨거 등록
- oauth 로그인 필터 스웨거 등록
- 테스트 결과 잘 붙습니당

66 add swagger openapi security

---

src/main/java/com/umc/yourweather/controller/UserController.java
src/main/java/com/umc/yourweather/response/SignupResponseDto.java
src/main/java/com/umc/yourweather/service/UserService.java

> body로 accessToken과 refreshToken을 이동했습니다.
- accessToken, refreshToken을 body로 이동

[FIX] access token move from header to body (signup)

---

src/main/java/com/umc/yourweather/controller/ReportController.java
src/main/java/com/umc/yourweather/controller/UserController.java
src/main/java/com/umc/yourweather/domain/entity/User.java
src/main/java/com/umc/yourweather/request/ChangeNicknameRequestDto.java
src/main/java/com/umc/yourweather/response/StatisticResponseDto.java
src/main/java/com/umc/yourweather/response/UserResponseDto.java
src/main/java/com/umc/yourweather/service/UserService.java

> 닉네임 변경 api와 그 외의 잡무를 해결했습니다.
- 닉네임 변경 api 추가
- 통계 소수점 처리
- NaN 반환 해결
- 그 외에는 api 설명 보강을 했습니다

[FEAT] add change nickname api and clear chores

---

src/main/java/com/umc/yourweather/request/MemoRequestDto.java

> hotfix: Memo entity의 content @NotBlank -> @Notnull로 변경

[hotfix] Memo entity의 content @NotBlank -> @Notnull로 변경

---

src/main/java/com/umc/yourweather/controller/MemoController.java
src/main/java/com/umc/yourweather/response/MemoResponseDto.java
src/main/java/com/umc/yourweather/service/MemoService.java

> memoId를 이용해 하나의 메모만을 반환하는 API입니다. 
- MemoResponse에 생성자를 Memo 엔티티를 끼우도록 수정하였습니다. (최종)
```
@Builder
public MemoResponseDto(Memo memo) {
this.status = memo.getStatus();
this.content = memo.getContent();
this.localDateTime = String.valueOf(memo.getCreatedDateTime());
this.temperature = memo.getTemperature();
}
```
- write에 빌더 코드 수정
```
return MemoResponseDto.builder()
.memo(memo)
.build();
```

[FEAT] getOneMemo by memoId

---

src/main/java/com/umc/yourweather/controller/WeatherController.java
src/main/java/com/umc/yourweather/domain/entity/User.java
src/main/java/com/umc/yourweather/domain/enums/Platform.java
src/main/java/com/umc/yourweather/request/SignupRequestDto.java
src/main/java/com/umc/yourweather/response/UserResponseDto.java
src/main/java/com/umc/yourweather/service/UserService.java

> 마이페이지 반환 api에 플랫폼 추가
- 마이페이지 반환 api에 플랫폼 추가
- UserResponse에 플랫폼 추가
- platform string에서 enums으로 변경
```
public enum Platform {
YOURWEATHER, KAKAO, NAVER, GOOGLE
}
```
- monthly api에 description 수정

[FIX] mypage api add platform

---

src/main/java/com/umc/yourweather/service/WeatherService.java

> home api 오류 해결 
> 2023-08-12 16:08:13.536 27491-27607 okhttp.OkHttpClient     com.umc.yourweather                  I  {"success":false,"code":400,"message":"query did not return a unique result: 3","result":null}
2023-08-12 16:08:13.547 27491-27607 HomeFragment            com.umc.yourweather                  E  홈 데이터가 null입니다.
-  home api에 User조건 추가
- findByDate -> findByDateAndUser
```
Weather weather = weatherRepository.findByDateAndUser(localDate,userDetails.getUser())
.orElseThrow(() -> new WeatherNotFoundException("해당 날짜에 해당하는 날씨 객체가 존재하지 않습니다."));
```

[HOTFIX] home api에 User조건 추가

---

src/main/java/com/umc/yourweather/controller/ReportController.java
src/main/java/com/umc/yourweather/service/ReportService.java
src/test/java/com/umc/yourweather/controller/ReportControllerTest.java
src/test/java/com/umc/yourweather/service/ReportServiceTest.java

> 주간 특정 날짜 조회 기능 추가
- 주간 특정 날짜 조회 기능
- 인수 테스트만 진행된 상태입니다. 이후에 테스트 코드를 만들어 커버리지를 채워보겠습니다.

[FEAT] get weekly specific weather

---

src/main/java/com/umc/yourweather/controller/MemoController.java
src/main/java/com/umc/yourweather/service/MemoService.java

> 같은 날짜에 메모를 10개 이상 기록하지 못하게 만듭니다.
- 같은 날짜에 메모를 10개 이상 기록 방지
- 인수 테스트 진행 완료했습니다!

[FIX] write notes up to 10 times

---

src/main/java/com/umc/yourweather/controller/MemoController.java
src/main/java/com/umc/yourweather/service/MemoService.java
src/main/java/com/umc/yourweather/service/WeatherService.java

> 하루의 Memo가 전부 삭제되면 Weather도 같이 삭제하도록 만들었습니다.
- 하루의 Memo가 전부 삭제되면 Weather도 같이 삭제
- 인수 테스트 진행했습니다!

[FIX] delete last memo with weather

---

src/main/java/com/umc/yourweather/controller/MemoController.java
src/main/java/com/umc/yourweather/controller/UserController.java
src/main/java/com/umc/yourweather/controller/WeatherController.java
src/main/java/com/umc/yourweather/service/WeatherService.java

> 스웨거를 보고 설명이 잘못된 부분(복붙이슈) 해결
> 각 api 제목에 "api"를 빼는 방향으로 통일감을 줬습니다.

[DOCS] description 수정

---

src/main/java/com/umc/yourweather/domain/MemoManager.java
src/main/java/com/umc/yourweather/response/HomeResponseDto.java
src/main/java/com/umc/yourweather/service/WeatherService.java

> home api에 어떤 백그라운드 이미지가 필요할지 계산해서 이미지 이름을 전달해줍니다
- 이미지 이름 전달 기능 추가
- 15 개의 파일 이름에 따른 15개의 분기를 처리하고 있습니다.
- 파일 이름에 대한 네이밍 규칙이 존재한다면 이렇게 많은 분기 없이 개발이 가능할 것 같습니다.
- 나중에 새로운 날씨 종류가 생긴다면 또 이 부분에 대한 분기를 만들어줘야하니 파일 네이밍 규칙 설정에 대한 부분은 선택이 아닌 필수로 보입니다.
- 이 부분은 프론트 분들과 논의해야하니 나중에 언급하도록 하겠습니다.

[FEAT] Enhance Home

---

src/main/java/com/umc/yourweather/controller/MemoController.java
src/main/java/com/umc/yourweather/response/MemoResponseDto.java
src/main/java/com/umc/yourweather/service/MemoService.java

> memo write response 부분에 weather Id를 돌려주도록 변경합니다
- weatherId 필드 추가
- MemoService의 getMemo 메서드에 있는 `@Transactinal` 어노테이션에 `readOnly = true` 프로퍼티를 추가해줬습니다.
- MemoResponseDto가 수정됨에 따라 MemoService의 getMemo 메서드에서 돌려주는 반환 값에도 weatherId를 추가하도록 수정해줬습니다.
-

[FIX] add weatherId at memo write response

---

src/main/java/com/umc/yourweather/api/RequestURI.java
src/main/java/com/umc/yourweather/config/SecurityConfig.java
src/main/java/com/umc/yourweather/controller/AdvertisementController.java
src/main/java/com/umc/yourweather/controller/UserController.java
src/main/java/com/umc/yourweather/domain/ReIssueTokenProvider.java
src/main/java/com/umc/yourweather/domain/ReIssuedToken.java
src/main/java/com/umc/yourweather/domain/entity/Advertisement.java
src/main/java/com/umc/yourweather/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/umc/yourweather/repository/AdvertisementRepository.java
src/main/java/com/umc/yourweather/repository/impl/AdvertisementRepositoryImpl.java
src/main/java/com/umc/yourweather/repository/jpa/AdvertisementJpaRepository.java
src/main/java/com/umc/yourweather/request/AddAdvertisementRequestDto.java
src/main/java/com/umc/yourweather/response/AddAdvertisementResponseDto.java
src/main/java/com/umc/yourweather/response/AdvertisementResponseDto.java
src/main/java/com/umc/yourweather/service/AdvertisementService.java
src/main/java/com/umc/yourweather/service/UserService.java

> 광고 버튼 누르면 특정 url로 연결해야함 아직은 광고주들과 컨택이 안 됐으니까 우리가 임의로 특정 url을 보내게 해야합니당
요약하자면 -> 광고주와 컨택이 되어 광고가 연결됐을 때 광고 링크를 전달할 기능을 추가해야함
> 이 기능을 만들기 위한 보일러 플레이팅을 주로 했습니다. 우리 서버에 광고에 관한 CRUD를 간단하게 만들어봤어요
> 만들면서 최종적으로 어떻게 요구사항을 충족시킬지를 생각해봤는데, 아무래도 카테고리를 추가해야할 것 같아요!
> 상황별 카테고리를 나누어 유저의 상태가 어떤 상태인지 프론트에서 받은 다음, 해당 상태에 맞는 카테고리를 매칭시켜 거기에 있는 데이터들을 랜덤으로 띄워주는 것이죠
> 이건 나중에 데모데이 끝나고 진행해보면 좋을 것 같습니다!
- 광고 get 요청 추가
- 간단한 CRUD 보일러 플레이팅

[FEAT] send advertisement url
